### ISSUE TITLE
Update site from Gatsby 2 to 4

### ISSUE THREAD

**Issue by julieg18** [iterative/cml.dev#163]

**Comment by casperdcl** [comment]
I assume related to #66 as well as NodeJS v16 support?

**Comment by yathomasi** [comment]
@iterative/websites I think this should be given more priority because it's not running on my machine 😁.
For now, at least upgrade the `gatsby-plugin-sharp` to a higher version that [has a higher dependency for sharp (>0.28)](https://github.com/lovell/sharp/issues/2460#issuecomment-811046375) and supports running on arm-based m1 chips.
But it would be better to upgrade as a whole.  I just checked over dvc.org and @rogermparent had done this mighty job over dvc.org 👏. It would be better if @rogermparent can help on this directly or provide the list of findings/learnings or considerations here so that anyone can start from there.

**Comment by julieg18** [comment]
> @iterative/websites I think this should be given more priority because it's not running on my machine 😁.

Agreed on making this more of a priority! Since me and Roger both worked on doing this with dvc.org, I can work on this after I finish my current P1 or I can help you if you want to take this one @yathomasi!

**Comment by jorgeorpinel** [comment]
> it's not running on my machine 😁.
For now, at least upgrade the gatsby-plugin-sharp to a higher version that has a higher dependency for sharp (>0.28) and supports running on arm-based m1 chips.

+1 (since I'm migrating to a new MacBook 😬)
